### ISSUE TITLE
Transcript needed for 10.2 10.3 and 10.4 

### ISSUE THREAD

**Issue by campaignupgrade** [podcasts-srt/mike-duncan-revolutions#1]
Hello, I could really use transcripts for 10.2 10.3 and 10.4. This is one the best descriptions of Marx's theory of capital I've heard. I'm looking into creating a graphic illustration from Mike's description.

**Comment by podcasts-srt** [comment]
https://github.com/podcasts-srt/mike-duncan-revolutions/blob/master/s10e02-The-Adventures-of-Karl-Marx-and-Friedrich-Engels.srt

https://github.com/podcasts-srt/mike-duncan-revolutions/blob/master/s10e03-The-Three-Pillars-of-Marxism.srt

https://github.com/podcasts-srt/mike-duncan-revolutions/blob/master/s10e04-Historical-Materialism.srt
